name: rentcar
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  flutter_screenutil: ^5.9.0
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
  

